### ISSUE TITLE
Consume the image upload API from within the "create alert" APIs to make things easier for the FE & Mobile guys

### ISSUE THREAD

**Issue by gdscfuto** [dscfuto-org/fasthrash-BE#16]
Call the image upload API from within the Alerts API to upload the image, get the URL and then store it in the database alongside other data in the alerts model

**Comment by starlingvibes** [comment]
Successfully implemented in commit: https://github.com/dscfuto-org/fasthrash-BE/commit/f2db9ad6d7ea2303aaf7706422f506d3f9efed95
