### ISSUE TITLE
Write documentation for the API endpoints at https://fastrash-1337.ew.r.appspot.com/

### ISSUE THREAD

**Issue by gdscfuto** [dscfuto-org/fasthrash-BE#9]

**Comment by uwaagbai1** [comment]
Implemented

**Comment by gdscfuto** [comment]
Seen, thanks so much! It would be helpful if there's sample parameters that are sent to the server when the user tries it out. That'll be awesome :-)

**Comment by uwaagbai1** [comment]
Okay, I'll make the necessary changes. Thanks
